[package]
name = "eip712"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "0.14.0"
ethers-derive-eip712 = "0.14.0"
